version: "1"

stacks:
    # The key of is the immutable slug of your stack
    # which you will find in the URL.
    pmm-ansible:
        environment:
            ANSIBLE_CONFIG: /mnt/workspace/source/pmm/ansible/ansible.cfg
